# api/config/packages/api_platform.yaml
api_platform:

  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header

  defaults:
    pagination_items_per_page: 2
    pagination_client_enabled: true